version: '3'
services:
    speedtest-to-discord:
        build:
            context: .
        image: ryanpage/speedtest-to-discord
        env_file: ./.env
        container_name: speedtest-to-discord
        restart: unless-stopped